### ISSUE TITLE
[PE-D][Tester C] Incomplete List of Commands in Help Window

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S1-CS2103T-T10-3/tp#104]
List of Commands in help window is incomplete compared to UG.

-------------
Labels: `type.DocumentationBug` `severity.Medium`
original: TZL0/ped#2

**Comment by glemenneo** [comment]
The Help Window in the jar file was not up to date. In the codebase, the Help Window was updated to reflect the complete list of commands.
