### ISSUE TITLE
[PE-D][Tester B] Help inconsistent with UG

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S1-CS2103T-T10-3/tp#106]
![image.png](https://raw.githubusercontent.com/ShawnChew/ped/main/files/1a131ec0-5dc1-43de-81a5-a24bed4d1efd.png)

![image.png](https://raw.githubusercontent.com/ShawnChew/ped/main/files/4fc50513-5037-4486-bdee-427587317efc.png)

Some of the naming of the fields are not the same as those mentioned in the UG. I think it will be better to keep them consistent.

-------------
Labels: `type.DocumentationBug` `severity.Low`
original: ShawnChew/ped#2

**Comment by glemenneo** [comment]
The Help Window in the jar file was not up to date. In the codebase, the Help Window was updated to reflect the complete list of commands.
