### ISSUE TITLE
[PE-D][Tester E] Very minor style issues in UG

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S1-CS2103T-T10-3/tp#134]
### Description

Some commas are not followed by a blank space
![Screenshot 2022-10-28 at 16.53.19.png](https://raw.githubusercontent.com/yuanxi1/ped/main/files/c9fbb99f-06d3-4dd6-8d15-b2c9b72ed6ed.png)

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`
original: yuanxi1/ped#6

**Comment by jacobkwan** [comment]
fixed in codebase already
